/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiPublicCloudinaryAuthRouteImport } from './routes/api/public/cloudinary/auth'
import { Route as ApiPublicCloudinaryFetchFlatFolderRouteImport } from './routes/api/public/cloudinary/fetch-flat-folder'
import { Route as ApiPublicCloudinarySearchByChassisRouteImport } from './routes/api/public/cloudinary/search-by-chassis'
import { Route as ApiPublicCloudinaryFoldersDateFolderRouteImport } from './routes/api/public/cloudinary/folders.$dateFolder'
import { Route as ApiPublicCloudinaryResourcesDateFolderSubfolderRouteImport } from './routes/api/public/cloudinary/resources.$dateFolder.$subfolder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinaryAuthRoute = ApiPublicCloudinaryAuthRouteImport.update({
  id: '/api/public/cloudinary/auth',
  path: '/api/public/cloudinary/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinaryFetchFlatFolderRoute =
  ApiPublicCloudinaryFetchFlatFolderRouteImport.update({
    id: '/api/public/cloudinary/fetch-flat-folder',
    path: '/api/public/cloudinary/fetch-flat-folder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudinarySearchByChassisRoute =
  ApiPublicCloudinarySearchByChassisRouteImport.update({
    id: '/api/public/cloudinary/search-by-chassis',
    path: '/api/public/cloudinary/search-by-chassis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudinaryFoldersDateFolderRoute =
  ApiPublicCloudinaryFoldersDateFolderRouteImport.update({
    id: '/api/public/cloudinary/folders/$dateFolder',
    path: '/api/public/cloudinary/folders/$dateFolder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudinaryResourcesDateFolderSubfolderRoute =
  ApiPublicCloudinaryResourcesDateFolderSubfolderRouteImport.update({
    id: '/api/public/cloudinary/resources/$dateFolder/$subfolder',
    path: '/api/public/cloudinary/resources/$dateFolder/$subfolder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/cloudinary/auth': typeof ApiPublicCloudinaryAuthRoute
  '/api/public/cloudinary/fetch-flat-folder': typeof ApiPublicCloudinaryFetchFlatFolderRoute
  '/api/public/cloudinary/search-by-chassis': typeof ApiPublicCloudinarySearchByChassisRoute
  '/api/public/cloudinary/folders/$dateFolder': typeof ApiPublicCloudinaryFoldersDateFolderRoute
  '/api/public/cloudinary/resources/$dateFolder/$subfolder': typeof ApiPublicCloudinaryResourcesDateFolderSubfolderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/cloudinary/auth': typeof ApiPublicCloudinaryAuthRoute
  '/api/public/cloudinary/fetch-flat-folder': typeof ApiPublicCloudinaryFetchFlatFolderRoute
  '/api/public/cloudinary/search-by-chassis': typeof ApiPublicCloudinarySearchByChassisRoute
  '/api/public/cloudinary/folders/$dateFolder': typeof ApiPublicCloudinaryFoldersDateFolderRoute
  '/api/public/cloudinary/resources/$dateFolder/$subfolder': typeof ApiPublicCloudinaryResourcesDateFolderSubfolderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/cloudinary/auth': typeof ApiPublicCloudinaryAuthRoute
  '/api/public/cloudinary/fetch-flat-folder': typeof ApiPublicCloudinaryFetchFlatFolderRoute
  '/api/public/cloudinary/search-by-chassis': typeof ApiPublicCloudinarySearchByChassisRoute
  '/api/public/cloudinary/folders/$dateFolder': typeof ApiPublicCloudinaryFoldersDateFolderRoute
  '/api/public/cloudinary/resources/$dateFolder/$subfolder': typeof ApiPublicCloudinaryResourcesDateFolderSubfolderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/public/cloudinary/auth'
    | '/api/public/cloudinary/fetch-flat-folder'
    | '/api/public/cloudinary/search-by-chassis'
    | '/api/public/cloudinary/folders/$dateFolder'
    | '/api/public/cloudinary/resources/$dateFolder/$subfolder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/public/cloudinary/auth'
    | '/api/public/cloudinary/fetch-flat-folder'
    | '/api/public/cloudinary/search-by-chassis'
    | '/api/public/cloudinary/folders/$dateFolder'
    | '/api/public/cloudinary/resources/$dateFolder/$subfolder'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/public/cloudinary/auth'
    | '/api/public/cloudinary/fetch-flat-folder'
    | '/api/public/cloudinary/search-by-chassis'
    | '/api/public/cloudinary/folders/$dateFolder'
    | '/api/public/cloudinary/resources/$dateFolder/$subfolder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiPublicCloudinaryAuthRoute: typeof ApiPublicCloudinaryAuthRoute
  ApiPublicCloudinaryFetchFlatFolderRoute: typeof ApiPublicCloudinaryFetchFlatFolderRoute
  ApiPublicCloudinarySearchByChassisRoute: typeof ApiPublicCloudinarySearchByChassisRoute
  ApiPublicCloudinaryFoldersDateFolderRoute: typeof ApiPublicCloudinaryFoldersDateFolderRoute
  ApiPublicCloudinaryResourcesDateFolderSubfolderRoute: typeof ApiPublicCloudinaryResourcesDateFolderSubfolderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/auth': {
      id: '/api/public/cloudinary/auth'
      path: '/api/public/cloudinary/auth'
      fullPath: '/api/public/cloudinary/auth'
      preLoaderRoute: typeof ApiPublicCloudinaryAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/fetch-flat-folder': {
      id: '/api/public/cloudinary/fetch-flat-folder'
      path: '/api/public/cloudinary/fetch-flat-folder'
      fullPath: '/api/public/cloudinary/fetch-flat-folder'
      preLoaderRoute: typeof ApiPublicCloudinaryFetchFlatFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/search-by-chassis': {
      id: '/api/public/cloudinary/search-by-chassis'
      path: '/api/public/cloudinary/search-by-chassis'
      fullPath: '/api/public/cloudinary/search-by-chassis'
      preLoaderRoute: typeof ApiPublicCloudinarySearchByChassisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/folders/$dateFolder': {
      id: '/api/public/cloudinary/folders/$dateFolder'
      path: '/api/public/cloudinary/folders/$dateFolder'
      fullPath: '/api/public/cloudinary/folders/$dateFolder'
      preLoaderRoute: typeof ApiPublicCloudinaryFoldersDateFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/resources/$dateFolder/$subfolder': {
      id: '/api/public/cloudinary/resources/$dateFolder/$subfolder'
      path: '/api/public/cloudinary/resources/$dateFolder/$subfolder'
      fullPath: '/api/public/cloudinary/resources/$dateFolder/$subfolder'
      preLoaderRoute: typeof ApiPublicCloudinaryResourcesDateFolderSubfolderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiPublicCloudinaryAuthRoute: ApiPublicCloudinaryAuthRoute,
  ApiPublicCloudinaryFetchFlatFolderRoute:
    ApiPublicCloudinaryFetchFlatFolderRoute,
  ApiPublicCloudinarySearchByChassisRoute:
    ApiPublicCloudinarySearchByChassisRoute,
  ApiPublicCloudinaryFoldersDateFolderRoute:
    ApiPublicCloudinaryFoldersDateFolderRoute,
  ApiPublicCloudinaryResourcesDateFolderSubfolderRoute:
    ApiPublicCloudinaryResourcesDateFolderSubfolderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
